version: "2.4"
services:
  tgto:
    image: heapy/tgto:${TGTO_RELEASE}
    container_name: tgto
    restart: always
    mem_limit: 256m
    memswap_limit: 0m
    ports:
    - "8090:8080"
    environment:
      TGTO_OPTS: ${TGTO_OPTS}
      TGTO_BOT_TOKEN: ${TGTO_BOT_TOKEN}
      TGTO_BOT_NAME: ${TGTO_BOT_NAME}
      TGTO_BASE_URL: ${TGTO_BASE_URL}
      TGTO_JDBC_URL: ${TGTO_JDBC_URL}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_RELEASE: ${TGTO_RELEASE}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
    depends_on:
    - tgto_database
  tgto_database:
    image: postgres:10.5
    container_name: tgto_database
    restart: always
    mem_limit: 128m
    memswap_limit: 0m
    user: "${TGTO_SYSTEM_USER}"
    environment:
      POSTGRES_PASSWORD: "tgto"
      POSTGRES_USER: "tgto"
      POSTGRES_DB: "tgto"
    volumes:
    - ${TGTO_DATA}/pgdata:/var/lib/postgresql/data
    - /etc/passwd:/etc/passwd:ro

