version: "3.3"
services:
  tgto:
    image: heapy/tgto:${TGTO_RELEASE}
    container_name: tgto
    restart: always
    ports:
    - "8090:8080"
    environment:
      TGTO_OPTS: ${TGTO_OPTS}
      TGTO_BOT_TOKEN: ${TGTO_BOT_TOKEN}
      SENTRY_DSN: ${TGTO_SENTRY_DSN}
      SENTRY_RELEASE: ${TGTO_RELEASE}
      SENTRY_ENVIRONMENT: ${TGTO_ENV}
    depends_on:
    - tgto_database
  tgto_database:
    image: postgres:10.5
    container_name: tgto_database
    restart: always
    user: "${TGTO_SYSTEM_USER}"
    environment:
      POSTGRES_PASSWORD: "tgto"
      POSTGRES_USER: "tgto"
      POSTGRES_DB: "tgto"
    volumes:
    - ${TGTO_DATA}/pgdata:/var/lib/postgresql/data
    - /etc/passwd:/etc/passwd:ro

