# docker-compose -f docker-compose-dev.yml up -d
version: "2.4"
services:
  tgto_database:
    image: postgres:10.5
    container_name: tgto_database
    restart: always
    mem_limit: 128m
    memswap_limit: 0m
    user: "${TGTO_SYSTEM_USER}"
    environment:
      POSTGRES_PASSWORD: "tgto"
      POSTGRES_USER: "tgto"
      POSTGRES_DB: "tgto"
    volumes:
     - ${TGTO_DATA}/pgdata:/var/lib/postgresql/data
     - /etc/passwd:/etc/passwd:ro
    ports:
      - "127.0.0.1:5436:5432"
