sudo: required

services:
  - docker

language: java

jdk:
  - openjdk11

script:
  - ./gradlew check installDist
  - docker build -t "heapy/tgto:b${TRAVIS_BUILD_NUMBER}" ./

deploy:
  provider: script
  script: bash devops/deploy.sh
  on:
    branch: master
