name: "Build"
on:
  - "push"
jobs:
  build:
    name: "Build on JDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk:
          - 11
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK ${{ matrix.jdk }}"
        uses: actions/setup-java@v2
        with:
          java-version: "${{ matrix.jdk }}"
          distribution: "zulu"
      - name: "Build with Gradle"
        run: ./gradlew check distTar
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "Kotlin Application"
          path: "build/distributions/tgto.tar"
          retention-days: 1
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: "Kotlin Application"
          path: "build/distributions/"
      - name: "Untar files"
        run: mkdir -p build/install && tar -xvf build/distributions/tgto.tar -C $_
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
          registry: ghcr.io
          repository: heapy/tgto
          tag_with_sha: true
          tag_with_ref: true
